<script setup lang="ts">
import { computed, onMounted, ref } from "vue";
import { Eye, LoaderCircle, RefreshCw, Trash2 } from "@lucide/vue";
import { invoke } from "@tauri-apps/api/core";
import MarkdownPreview from "../components/MarkdownPreview.vue";
import { deleteInstallationRecords, loadInstallationRecords } from "../lib/database";
import type { InstallationRecord, PreparedUninstall, TargetId, TargetSkillInventory } from "../types/skill";

const records = ref<InstallationRecord[]>([]); const inventory = ref<TargetSkillInventory[]>([]); const loading = ref(false); const working = ref<string | null>(null); const error = ref<string | null>(null); const preview = ref<{ name: string; content: string } | null>(null);
const targets: TargetId[] = ["claude_code", "codex_cli", "codex_desktop", "claude_desktop"];
const labels: Record<TargetId, string> = { claude_code: "Claude Code", codex_cli: "Codex CLI", codex_desktop: "Codex Desktop", claude_desktop: "Claude Desktop" };
const rows = computed(() => {
  const names = new Set([...records.value.map(r => r.directory_name), ...inventory.value.flatMap(i => i.skills.map(s => s.directory_name))]);
  return [...names].sort().map(directory_name => ({ directory_name, records: records.value.filter(r => r.directory_name === directory_name), live: targets.filter(id => inventory.value.find(i => i.id === id)?.skills.some(s => s.directory_name === directory_name)) }));
});
async function load() { loading.value = true; error.value = null; try { [records.value, inventory.value] = await Promise.all([loadInstallationRecords(), invoke<TargetSkillInventory[]>("list_installed_skills")]); } catch (cause) { error.value = String(cause); } finally { loading.value = false; } }
async function showPreview(name: string, target: TargetId) { try { preview.value = { name, content: await invoke<string>("read_installed_skill_markdown", { target, directoryName: name }) }; } catch (cause) { error.value = String(cause); } }
async function uninstall(row: { directory_name: string; records: InstallationRecord[]; live: TargetId[] }) { if (!row.live.length || working.value) return; working.value = row.directory_name; error.value = null; let prepared: PreparedUninstall | null = null; try { prepared = await invoke<PreparedUninstall>("prepare_skill_uninstall", { directoryName: row.directory_name, targets: row.live }); const dbTargets = row.records.filter(r => r.status === "installed").map(r => r.target); await deleteInstallationRecords(row.directory_name, dbTargets); await invoke("commit_skill_uninstall", { token: prepared.token }); await load(); } catch (cause) { if (prepared) try { await invoke("rollback_skill_uninstall", { token: prepared.token }); } catch {} error.value = String(cause); } finally { working.value = null; } }
onMounted(() => { void load(); });
</script>
<template><section class="mx-auto w-full max-w-6xl px-6 py-8 lg:px-10"><div class="mb-7 flex items-end justify-between gap-4"><div><p class="mb-2 text-xs font-semibold uppercase tracking-[0.18em] text-teal-700">Manage</p><h1 class="text-3xl font-semibold text-slate-950">已安装 Skill</h1><p class="mt-2 text-sm text-slate-500">矩阵以本机实际目录为准；Claude Desktop 的 zip 仅显示为待上传。</p></div><button class="flex size-9 items-center justify-center border border-slate-300 bg-white text-slate-600" title="刷新" :disabled="loading" @click="load"><RefreshCw class="size-4" :class="loading && 'animate-spin'" /></button></div><p v-if="error" class="mb-4 border-l-4 border-rose-500 bg-rose-50 p-3 text-sm text-rose-900">{{ error }}</p><div class="overflow-x-auto border border-slate-200 bg-white"><table class="min-w-full text-left text-sm"><thead class="bg-slate-50 text-xs text-slate-500"><tr><th class="px-4 py-3">Skill</th><th v-for="target in targets" :key="target" class="px-3 py-3">{{ labels[target] }}</th><th class="px-3 py-3">操作</th></tr></thead><tbody><tr v-for="row in rows" :key="row.directory_name" class="border-t border-slate-200"><td class="px-4 py-3 font-medium text-slate-900">{{ row.records[0]?.skill_name ?? row.directory_name }}<p v-if="row.records.some(r => r.commit_sha !== '')" class="mt-1 text-xs font-normal text-slate-500">{{ row.directory_name }}</p></td><td v-for="target in targets" :key="target" class="px-3 py-3"><span v-if="row.live.includes(target)" class="text-emerald-700">已安装</span><span v-else-if="row.records.some(r => r.target === target && r.status === 'packaged_for_upload')" class="text-amber-700">待上传</span><span v-else-if="row.records.some(r => r.target === target)" class="text-rose-700">记录缺失</span><span v-else class="text-slate-300">-</span></td><td class="px-3 py-3"><div class="flex gap-2"><button v-if="row.live.length" class="flex size-8 items-center justify-center border border-slate-300" title="预览 SKILL.md" @click="showPreview(row.directory_name, row.live[0])"><Eye class="size-4" /></button><button v-if="row.live.length" class="flex size-8 items-center justify-center border border-rose-200 text-rose-700 disabled:opacity-50" title="卸载本地副本" :disabled="working === row.directory_name" @click="uninstall(row)"><LoaderCircle v-if="working === row.directory_name" class="size-4 animate-spin" /><Trash2 v-else class="size-4" /></button></div></td></tr><tr v-if="!loading && !rows.length"><td colspan="6" class="px-4 py-12 text-center text-slate-500">尚未检测到本地 skill。</td></tr></tbody></table></div><section v-if="preview" class="mt-6 border border-slate-200 bg-white"><div class="flex items-center justify-between border-b border-slate-200 px-4 py-3"><h2 class="font-semibold">{{ preview.name }} / SKILL.md</h2><button class="text-sm text-slate-500" @click="preview = null">关闭</button></div><MarkdownPreview :content="preview.content" /></section></section></template>
