<script setup lang="ts">
import { onMounted, ref } from "vue";
import { Check, LoaderCircle, Save, Settings2 } from "@lucide/vue";
import { invoke } from "@tauri-apps/api/core";
import type { ApiConfig, AppSettings } from "../types/skill";
const empty = (): ApiConfig => ({ format: "openai", apiUrl: "", apiKey: "", model: "" });
const settings = ref<AppSettings>({ deepScan: empty(), prompt: empty() }); const loading = ref(true); const saving = ref(false); const saved = ref(false); const error = ref<string | null>(null);
async function load() { loading.value = true; try { settings.value = await invoke<AppSettings>("get_settings"); } catch (cause) { error.value = String(cause); } finally { loading.value = false; } }
async function save() { saving.value = true; error.value = null; try { await invoke("save_settings", { settings: settings.value }); saved.value = true; window.setTimeout(() => { saved.value = false; }, 1600); } catch (cause) { error.value = String(cause); } finally { saving.value = false; } }
onMounted(() => { void load(); });
</script>
<template><section class="mx-auto w-full max-w-4xl px-6 py-8 lg:px-10"><div class="mb-7"><p class="mb-2 text-xs font-semibold uppercase tracking-[0.18em] text-teal-700">Settings</p><h1 class="text-3xl font-semibold text-slate-950">模型设置</h1><p class="mt-2 text-sm text-slate-500">分别配置深度扫描与 Prompt 精炼。支持 OpenAI 兼容接口和 Anthropic Messages 接口。</p></div><p v-if="error" class="mb-4 border-l-4 border-rose-500 bg-rose-50 p-3 text-sm text-rose-900">{{ error }}</p><div v-if="loading" class="flex items-center gap-2 text-sm text-slate-500"><LoaderCircle class="size-4 animate-spin" />正在读取设置</div><div v-else class="space-y-5"><section v-for="(config, key) in settings" :key="key" class="border border-slate-200 bg-white p-5"><h2 class="flex items-center gap-2 font-semibold text-slate-900"><Settings2 class="size-4 text-teal-700" />{{ key === 'deepScan' ? '深度扫描模型' : 'Prompt 精炼模型' }}</h2><div class="mt-4 grid gap-4 sm:grid-cols-2"><label class="text-sm text-slate-700">接口格式<select v-model="config.format" class="mt-1 h-10 w-full border border-slate-300 bg-white px-2"><option value="openai">OpenAI 兼容</option><option value="anthropic">Anthropic Messages</option></select></label><label class="text-sm text-slate-700">模型（可选）<input v-model="config.model" class="mt-1 h-10 w-full border border-slate-300 px-2" placeholder="例如 gpt-4o-mini" /></label><label class="text-sm text-slate-700 sm:col-span-2">API URL<input v-model="config.apiUrl" class="mt-1 h-10 w-full border border-slate-300 px-2" placeholder="https://api.openai.com/v1" /></label><label class="text-sm text-slate-700 sm:col-span-2">API Key<input v-model="config.apiKey" type="password" class="mt-1 h-10 w-full border border-slate-300 px-2" autocomplete="off" /></label></div></section><button type="button" class="inline-flex h-10 items-center gap-2 bg-teal-600 px-4 text-sm font-medium text-white disabled:bg-slate-300" :disabled="saving" @click="save"><LoaderCircle v-if="saving" class="size-4 animate-spin" /><Check v-else-if="saved" class="size-4" /><Save v-else class="size-4" />{{ saved ? '已保存' : '保存设置' }}</button></div></section></template>
